import { createFileRoute } from "@tanstack/react-router";
import { ForensicWorkspace } from "@/components/ForensicWorkspace";
import { ShieldAlert } from "lucide-react";

export const Route = createFileRoute("/")({
  component: Index,
  head: () => ({
    meta: [
      { title: "Sentinel · Forensic Composite Workbench" },
      { name: "description", content: "AI-assisted forensic face sketch generation and suspect matching prototype." },
    ],
  }),
});

function Index() {
  return (
    <div className="min-h-screen">
      <header className="border-b border-border bg-card/50 backdrop-blur">
        <div className="max-w-[1600px] mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="h-9 w-9 rounded bg-gradient-to-br from-primary to-accent flex items-center justify-center text-primary-foreground font-display font-bold">S</div>
            <div>
              <h1 className="font-display tracking-[0.25em] text-sm">SENTINEL · DIV. 7</h1>
              <p className="text-[10px] text-muted-foreground tracking-widest font-display">FORENSIC COMPOSITE WORKBENCH</p>
            </div>
          </div>
          <div className="hidden md:flex items-center gap-2 text-xs text-muted-foreground font-display">
            <span className="h-2 w-2 rounded-full bg-primary animate-pulse" />
            CASE #2026-0507-A
          </div>
        </div>
      </header>

      <main className="max-w-[1600px] mx-auto px-6 py-8">
        <div className="mb-6 flex items-start gap-3 p-3 border border-border rounded bg-card/40">
          <ShieldAlert className="h-4 w-4 text-primary mt-0.5 shrink-0" />
          <p className="text-xs text-muted-foreground">
            <span className="text-foreground font-medium">Prototype demo.</span> Sketches are generated by an AI image model from witness descriptors. The mugshot database below is fictional and matches are a heuristic for demonstration only — not for real investigative use.
          </p>
        </div>

        <ForensicWorkspace />

        <footer className="mt-12 pt-6 border-t border-border text-[10px] font-display tracking-widest text-muted-foreground text-center">
          SENTINEL PROTOTYPE · FOR RESEARCH USE ONLY · NO REAL PERSONS DEPICTED
        </footer>
      </main>
    </div>
  );
}
